SELECT [Id]
      ,[WithheldBatchId]
      ,[BatchId]
      ,[BatchFilename]
      ,[LineType]
      ,[InvoiceNumber]
      ,[InvoiceVersion]
      ,[ClaimNumber]
      ,[FRN]
      ,[PaymentType]
      ,[PaymentSchedule]
      ,[TotalValue]
      ,[DeliveryBodyCode]
      ,[PaymentPreferenceCurrency]
      ,[CalculationCurrency]
      ,[Reason]
      ,[MarkedForRelease]
      ,[DateMarkedForRelease]
      ,[Released]
      ,[DateReleased]
  FROM [DEFRA.Payments.SFI].[dbo].[WithheldPayee]
  WHERE Released = 0
